from pathlib import Path
path = Path('src/pages/Orders.js')
text = path.read_text(encoding='utf-8')
old = "          {items.map((it) => (\n            <div key={it._id || it.product} className=\"d-flex align-items-center\" style={{ padding: 8, borderBottom: '1px solid #f2f2f2' }}>\n              <div style={{ width: 64, height: 64, marginInlineEnd: 12, background: '#fafafa', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n                {it.imageUrl ? <img src={it.imageUrl} alt={it.Name || ''} style={{ maxWidth: '100%', maxHeight: '100%' }} /> : <div style={{ fontSize: 11, color: '#999' }}>\u0628\u062f\u0648\u0646 \u0635\u0648\u0631\u0629</div>}\n              </div>\n              <div style={{ flex: 1 }}>\n                <div style={{ fontWeight: 700 }}>{it.Name || it.productName} <span className=\"text-muted\" style={{ fontWeight: 400 }}>x{it.quantity}</span></div>\n                <div className=\"text-muted\">\u062c.\u0645 {it.price} \u0644\u0644\u0642\u0637\u0639\u0629</div>\n              </div>\n              <div style={{ width: 120, textAlign: 'left' }}>\u062c.\u0645 {(it.price * (it.quantity || 1)).toFixed(2)}</div>\n            </div>\n          ))\n"
new = "          {items.map((it) => {\n            const details = it.productDetails || {};\n            const unitPrice = details.Sell ?? details.sell ?? it.price ?? 0;\n            return (\n              <div key={it._id || it.product} className=\"d-flex align-items-center\" style={{ padding: 8, borderBottom: '1px solid #f2f2f2' }}>\n                <div style={{ width: 64, height: 64, marginInlineEnd: 12, background: '#fafafa', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>\n                  {it.imageUrl ? <img src={it.imageUrl} alt={details.Name || it.Name || ''} style={{ maxWidth: '100%', maxHeight: '100%' }} /> : <div style={{ fontSize: 11, color: '#999' }}>بدون صورة</div>}\n                </div>\n                <div style={{ flex: 1 }}>\n                  <div style={{ fontWeight: 700 }}>{details.Name || it.Name || it.productName || 'منتج'} <span className=\"text-muted\" style={{ fontWeight: 400 }}>x{it.quantity}</span></div>\n                  <div className=\"text-muted\">{currency(unitPrice)} للوحدة</div>\n                </div>\n                <div style={{ width: 120, textAlign: 'left' }}>{currency(unitPrice * (it.quantity || 1))}</div>\n              </div>\n            );\n          })\n"
if old not in text:
    raise SystemExit('old block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
